#### **Working with Strings**

In [ ]:
full_name = "Abdulkadar Kapasi"

In [ ]:
print(type(full_name))

<class 'str'>


In [ ]:
firstName = "Abdulkadar"
lastName = "Kapasi"

In [ ]:
fullName = firstName + " " + lastName

In [ ]:
print(fullName)

Abdulkadar Kapasi


In [ ]:
fullName.upper()

'ABDULKADAR KAPASI'

In [ ]:
fullName.lower()

'abdulkadar kapasi'

In [ ]:
greetings = "Hello " + full_name + " nice to meet you!"

In [ ]:
print(greetings)

Hello Abdulkadar Kapasi nice to meet you!


In [ ]:
"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,oct,Nov,Dec".split(',')

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'oct',
 'Nov',
 'Dec']

In [ ]:
string = "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,oct,Nov,Dec"
string.split(',')

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'oct',
 'Nov',
 'Dec']

In [ ]:
string1 = "     Hello this is Abdulkadar Kapasi feeling great to see you all      "
print(string1)

     Hello this is Abdulkadar Kapasi feeling great to see you all      


In [ ]:
string1.strip() # remove the blank spaces from the front and the end.

'Hello this is Abdulkadar Kapasi feeling great to see you all'

In [ ]:
costof_IceCreame = 65
profit_margin = .20
numberof_IceCreame = 350

output_template = """If a grocery store sales Ice Creame at Rs. {} per piece, with the
profit margin of {} %, then the total profit it makes by selling {} ice creames is Rs. {}."""

In [ ]:
total_profit = costof_IceCreame * profit_margin * numberof_IceCreame
output = output_template.format(costof_IceCreame, profit_margin*100, numberof_IceCreame, total_profit)

In [ ]:
print(output)

If a grocery store sales Ice Creame at Rs. 65 per piece, with the
profit margin of 20.0 %, then the total profit it makes by selling 350 ice creames is Rs. 4550.0.


#### **Working with List**

In [ ]:
# List is ordered
fruits = ["apple", "banana", "orange", "grapes", "mango"]
print(fruits)

['apple', 'banana', 'orange', 'grapes', 'mango']


In [ ]:
fruits[0]

'apple'

In [ ]:
fruits[4]

'mango'

In [ ]:
fruits[1:3]

['banana', 'orange']

In [ ]:
fruits[:-1]

['apple', 'banana', 'orange', 'grapes']

In [ ]:
fruits.count("apple")

1

In [ ]:
fruits.insert(3, "strawberry")

In [ ]:
print(fruits)

['apple', 'banana', 'orange', 'strawberry', 'grapes', 'mango']


In [ ]:
fruits.append("pineapple")

In [ ]:
print(fruits)

['apple', 'banana', 'orange', 'strawberry', 'grapes', 'mango', 'pineapple']


In [ ]:
fruits.pop()

'pineapple'

In [ ]:
fruits.pop(1)

'banana'

In [ ]:
fruits.remove("orange")

In [ ]:
print(fruits)

['apple', 'strawberry', 'grapes', 'mango']


In [ ]:
# print the list using for loop
for i in fruits:
  print(i)

apple
strawberry
grapes
mango


In [ ]:
mixed_list = [1, "Hello", None, 3.16, fruits, 3 >= 6]
print(mixed_list)

[1, 'Hello', None, 3.16, ['apple', 'strawberry', 'grapes', 'mango'], False]


In [ ]:
len(fruits)

4

In [ ]:
len(mixed_list)

6

In [ ]:
fruits

['apple', 'strawberry', 'grapes', 'mango']

In [ ]:
fruits[1] = "blueberry"
print(fruits)

['apple', 'blueberry', 'grapes', 'mango']


In [ ]:
"apple" in fruits

True

In [ ]:
# List concatenation
more_fruits = fruits + ["orange", "pineapple", "banana"] + ["alphonso", "hapus", "sugarcane"]

In [ ]:
print(more_fruits) 

['apple', 'blueberry', 'grapes', 'mango', 'orange', 'pineapple', 'banana', 'alphonso', 'hapus', 'sugarcane']


In [ ]:
fruits.append(more_fruits)
print(fruits)

['apple', 'blueberry', 'grapes', 'mango', ['apple', 'blueberry', 'grapes', 'mango', 'orange', 'pineapple', 'banana', 'alphonso', 'hapus', 'sugarcane']]


In [ ]:
fruits.pop(4)
print(fruits)

['apple', 'blueberry', 'grapes', 'mango']


In [ ]:
new_fruits = ["alphonso", "sugarcane", "pineapple", "orange"]
fruits.extend(new_fruits)

In [ ]:
fruits.index("orange", 0, 10) # returns the index of the value

7

In [ ]:
fruits

['apple',
 'blueberry',
 'grapes',
 'mango',
 'alphonso',
 'sugarcane',
 'pineapple',
 'orange']

In [ ]:
fruits_copy = fruits.copy()

In [ ]:
fruits_copy

['apple',
 'blueberry',
 'grapes',
 'mango',
 'alphonso',
 'sugarcane',
 'pineapple',
 'orange']

In [ ]:
fruits.clear() # delete all the elements from the list

In [ ]:
fruits

[]

In [ ]:
more_fruits

['apple',
 'blueberry',
 'grapes',
 'mango',
 'orange',
 'pineapple',
 'banana',
 'alphonso',
 'hapus',
 'sugarcane']

In [ ]:
type(fruits_copy)

list

In [ ]:
fruits_copy.sort(reverse = True)

In [ ]:
fruits_copy

['sugarcane',
 'pineapple',
 'orange',
 'mango',
 'grapes',
 'blueberry',
 'apple',
 'alphonso']

#### **Working with Tuple**

In [ ]:
fruits = ("apple", "grapes", "mango", "cherry", "banana")
len(fruits)

5

In [ ]:
fruits[0]

'apple'

In [ ]:
fruits[4]

'banana'

In [ ]:
fruits[-2]

'cherry'

In [ ]:
fruits[1:4]

('grapes', 'mango', 'cherry')

In [ ]:
"mango" in fruits

True

In [ ]:
# fruits[0] = "coconut" # tuple doesn't allow to change the element

In [ ]:
fruits.count("cherry")

1

In [ ]:
fruits.index("mango", 0, 8)

2

#### **Working with Dictionary**

In [ ]:
employee = {'name':['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty'],
            'gender':['male', 'male', 'male', 'female', 'female'],
            'age':[21, 20, 23, 20, 24],
            'address':['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi'],
            'married':[True, True, False, True, False]}

In [ ]:
department = {'dept_name':['finance', 'marketing', 'technology', 'human resourse', 'finance'],
              'designation':['finance analyst', 'marketing specialist', 'software developer', 'hiring manager', 'audit manager'],
              'salary':[35000, 65000, 23000, 45000, 50000],
              'work Experience (years)':[3, 6, 1, 3.5, 5],
              'company':['amazon', 'google', 'adobe', 'samsung', 'philips']}

In [ ]:
print(employee)

{'name': ['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty'], 'gender': ['male', 'male', 'male', 'female', 'female'], 'age': [21, 20, 23, 20, 24], 'address': ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi'], 'married': [True, True, False, True, False]}


In [ ]:
print(department)

{'dept_name': ['finance', 'marketing', 'technology', 'human resourse', 'finance'], 'designation': ['finance analyst', 'marketing specialist', 'software developer', 'hiring manager', 'audit manager'], 'salary': [35000, 65000, 23000, 45000, 50000], 'work Experience (years)': [3, 6, 1, 3.5, 5], 'company': ['amazon', 'google', 'adobe', 'samsung', 'philips']}


In [ ]:
type(employee)

dict

In [ ]:
type(department)

dict

In [ ]:
employee['name']

['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty']

In [ ]:
department['designation']

['finance analyst',
 'marketing specialist',
 'software developer',
 'hiring manager',
 'audit manager']

In [ ]:
employee.get('name')

['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty']

In [ ]:
employee.get('address')

['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi']

In [ ]:
employee.items()

dict_items([('name', ['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty']), ('gender', ['male', 'male', 'male', 'female', 'female']), ('age', [21, 20, 23, 20, 24]), ('address', ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi']), ('married', [True, True, False, True, False])])

In [ ]:
employee.values()

dict_values([['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty'], ['male', 'male', 'male', 'female', 'female'], [21, 20, 23, 20, 24], ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi'], [True, True, False, True, False]])

In [ ]:
employee.keys()

dict_keys(['name', 'gender', 'age', 'address', 'married'])

In [ ]:
'address' in employee

True

In [ ]:
'sex' in employee

False

In [ ]:
print(employee.values())

dict_values([['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty'], ['male', 'male', 'male', 'female', 'female'], [21, 20, 23, 20, 24], ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi'], [True, True, False, True, False]])


In [ ]:
list(employee.items())[1]

('gender', ['male', 'male', 'male', 'female', 'female'])

In [ ]:
employee.update({'empid':[101, 102, 103, 104, 105]}) # updating the dictionary

In [ ]:
print(employee)

{'name': ['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty'], 'gender': ['male', 'male', 'male', 'female', 'female'], 'age': [21, 20, 23, 20, 24], 'address': ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi'], 'married': [True, True, False, True, False], 'empid': [101, 102, 103, 104, 105]}


#### **Working with if else statements**

In [ ]:
n = 18
if n % 2 == 0:
  print("The given number {} is even." .format(n))
else:
  print("The given number {} is odd." .format(n))

The given number 18 is even.


In [ ]:
n = int(input("Enter a number: "))
if n % 2 == 0:
  print("The given number {} is even." .format(n))
else:
  print("The given number {} is odd." .format(n))

Enter a number: 5
The given number 5 is odd.


In [ ]:
fruit_list = ['apple', 'mango', 'banana', 'grapes', 'strawberry']
fruit = input("Enter a fruit of your choice: ")
if fruit in fruit_list:
  print("The fruit {} is present in the stock." .format(fruit))
else:
  print("Sorry the fruit {} is not present in the stock." .format(fruit))


Enter a fruit of your choice: cherry
Sorry the fruit cherry is not present in the stock.


In [ ]:
fruit_list = ['apple', 'mango', 'banana', 'grapes', 'strawberry']
fruit = input("Enter a fruit of your choice: ")
print(end = '\n')
if fruit in fruit_list:
  print("The fruit {} is present in the stock." .format(fruit))
else:
  print("Sorry the fruit {} is not present in the stock instead the available fruits are: \n{}" .format(fruit, fruit_list))

Enter a fruit of your choice: mango

The fruit mango is present in the stock.


In [ ]:
n1 = float(input("Enter a number: "))
n2 = float(input("Enter a second number: "))
operator = input("Enter an operator: ['+' '-' '*' '/' '**' '%']: ")

if operator == '+':
  print("The addition of {} {} {} = {}" .format(n1, operator, n2, n1 + n2))

elif operator == '-':
  print("The substraction of {} {} {} = {}" .format(n1, operator, n2, n1 - n2))

elif operator == '*':
  print("The multiplication of {} {} {} = {}" .format(n1, operator, n2, n1 * n2))

elif operator == '/':
  print("The division of {} {} {} = {}" .format(n1, operator, n2, n1 / n2))

elif operator == '**':
  print("The power of {} {} {} = {}" .format(n1, operator, n2, n1 ** n2))

elif operator == '%':
  print("The remainder of {} {} {} = {}" .format(n1, operator, n2, n1 % n2))

else:
  print("invalid input")


Enter a number: 8
Enter a second number: 7
Enter an operator: ['+' '-' '*' '/' '**' '%']: *
The multiplication of 8.0 * 7.0 = 56.0


In [ ]:
n = 21

if n % 2 == 0:
  var = 'even'
else:
  var = 'odd'

print("The number {} is {}" .format(n, var))

The number 21 is odd


#### **Working with Loops**

In [ ]:
factorial = 1
i = 1

while i <= 5:
  factorial = factorial * i
  i = i + 1
  
print("The factorial of a 100 is : {}" .format(factorial))

The factorial of a 100 is : 120


In [ ]:
%%time
n = int(input("Enter a number: "))
factorial = 1
i = 1

while i <= n:
  factorial = factorial * i
  i = i + 1

print("The factorial of a {} is: {}" .format(n, factorial))


Enter a number: 6
The factorial of a 6 is: 720
CPU times: user 71.9 ms, sys: 20.1 ms, total: 91.9 ms
Wall time: 4.29 s


In [ ]:
pattern = '*'
length = 10

while len(pattern) <= length:
  print(pattern)
  pattern += '*'

while len(pattern) > 0:
  print(pattern)
  pattern = pattern[:-1]

*
**
***
****
*****
******
*******
********
*********
**********
***********
**********
*********
********
*******
******
*****
****
***
**
*


In [ ]:
n = 2
i = 1

while i <= 10:
  print("{} * {} =  {}" .format(n, i, n * i))
  i += 1

2 * 1 =  2
2 * 2 =  4
2 * 3 =  6
2 * 4 =  8
2 * 5 =  10
2 * 6 =  12
2 * 7 =  14
2 * 8 =  16
2 * 9 =  18
2 * 10 =  20


In [ ]:
n = int(input("Enter a number: "))
i = 1

while i <= 10:
  print("{} x {} = {}" .format(n, i, n * i))
  i += 1

Enter a number: 9
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


In [ ]:
# print first 10 even numbers
i = 1

while i <= 20:
  if i % 2 == 0:
    print(i)
  i += 1

2
4
6
8
10
12
14
16
18
20


In [ ]:
# print first 10 odd numbers
i = 1

while i <= 20:
  if i % 2 != 0:
    print(i)
  i += 1

1
3
5
7
9
11
13
15
17
19


In [ ]:
# print first 10 numbers square
i = 1

while i <= 10:
   print(i ** 2)
   i += 1

1
4
9
16
25
36
49
64
81
100


In [ ]:
# print series like 10, 20, 30, ....300
for i in range(31):
  print(i * 10)

0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300


In [ ]:
series = []

for i in range(31):
  series.append(i*10)
print(series)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300]


In [ ]:
# print series like 105, 98, 91....7
series = []
i = 105

while i >= 1:
  series.append(i)
  i -= 7
print(series)

[105, 98, 91, 84, 77, 70, 63, 56, 49, 42, 35, 28, 21, 14, 7]


In [ ]:
# print first 10 natural numbers in reverse order
i = 10
 
while i >= 1:
  print(i)
  i -= 1

10
9
8
7
6
5
4
3
2
1


In [ ]:
# print sum of first 10 natural numbers
sum = 0
i = 1

while i <= 10:
  sum += i
  i += 1
print(sum)

55


In [ ]:
sum = 0
i = 1

while i <= 20:
  if i % 2 == 0:
    sum += i
  i += 1
print(sum)

110


In [ ]:
n1 = int(input("Enter a number: "))
remainder = 0
sum = 0

while n1 != 0:
  remainder = n1 % 10
  sum = sum + remainder
  n1 = n1 // 10
print("The sum of digits are: ", sum)


Enter a number: 24
The sum of digits are:  6


In [ ]:
bool_value = 'y'
sum = 0

while bool_value.lower() == 'y':
  n = int(input("Enter any natural number of your choice: "))
  sum += n
  bool_value = input("Do you wnat to continue: (y or n): ")
print("Sum of all numbers is: ", sum)


Enter any natural number of your choice: 8
Do you wnat to continue: (y or n): y
Enter any natural number of your choice: 65
Do you wnat to continue: (y or n): n
Sum of all numbers is:  73


In [ ]:
i = 1
result = 1

while i <= 60:
  result *= i
  if i == 7:
    print("Magic number 52 reached! ...Execution stoped")
    break
  i += 1
print('i:', i)
print('result:', result)

Magic number 52 reached! ...Execution stoped
i: 7
result: 5040


In [ ]:
i = 1
result = 1

while i < 20:
  i += 1
  if i % 2 == 0:
    print("Skipping {}" .format(i))
    continue
  print("Multiplying with {}" .format(i))
  result *= i
print('i:', i)
print('result:', result)

Skipping 2
Multiplying with 3
Skipping 4
Multiplying with 5
Skipping 6
Multiplying with 7
Skipping 8
Multiplying with 9
Skipping 10
Multiplying with 11
Skipping 12
Multiplying with 13
Skipping 14
Multiplying with 15
Skipping 16
Multiplying with 17
Skipping 18
Multiplying with 19
Skipping 20
i: 20
result: 654729075


In [ ]:
courses = ['Data Science', 'Machine Learning', 'Python', 'Java', 'Scala', 'Deep Learning', 'SQL']

for i in courses:
  print(i)

Data Science
Machine Learning
Python
Java
Scala
Deep Learning
SQL


In [ ]:
for char in 'Saturday':
  print(char)

S
a
t
u
r
d
a
y


In [ ]:
for f in ['apple', 'banana', 'watermelon', 'pineapple', 'orange']:
  print(f)

apple
banana
watermelon
pineapple
orange


In [ ]:
# looping over a dictionary
for key in employee:
  print('Key:', key, ',', 'Value:', employee[key])

Key: name , Value: ['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty']
Key: gender , Value: ['male', 'male', 'male', 'female', 'female']
Key: age , Value: [21, 20, 23, 20, 24]
Key: address , Value: ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi']
Key: married , Value: [True, True, False, True, False]
Key: empid , Value: [101, 102, 103, 104, 105]


In [ ]:
for value in employee.values():
  print(value)

['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty']
['male', 'male', 'male', 'female', 'female']
[21, 20, 23, 20, 24]
['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi']
[True, True, False, True, False]
[101, 102, 103, 104, 105]


In [ ]:
for key_value in employee.items():
  print(key_value)

('name', ['ajay verma', 'gopal sharma', 'manoj kumar', 'shalini verma', 'shreya shetty'])
('gender', ['male', 'male', 'male', 'female', 'female'])
('age', [21, 20, 23, 20, 24])
('address', ['mumbai', 'pune', 'lucknow', 'chandigarh', 'delhi'])
('married', [True, True, False, True, False])
('empid', [101, 102, 103, 104, 105])


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(1, 8):
  print(i)

1
2
3
4
5
6
7


In [ ]:
for i in range(1, 30, 4):
  print(i)

1
5
9
13
17
21
25
29


In [ ]:
a = set()
for i in range(2, 25, 3):
  a.add(i)
print(a)

{2, 5, 8, 11, 14, 17, 20, 23}


In [ ]:
animals = ['tiger', 'lion', 'crocodile', 'snake', 'monkey', 'panda', 'horse']
for i in range(len(animals)):
  print("The animal at position {} is {}" .format(i, animals[i]))

The animal at position 0 is tiger
The animal at position 1 is lion
The animal at position 2 is crocodile
The animal at position 3 is snake
The animal at position 4 is monkey
The animal at position 5 is panda
The animal at position 6 is horse


In [ ]:
for i, value in enumerate(animals):
  print("The animal at position {} is {}" .format(i, value))

The animal at position 0 is tiger
The animal at position 1 is lion
The animal at position 2 is crocodile
The animal at position 3 is snake
The animal at position 4 is monkey
The animal at position 5 is panda
The animal at position 6 is horse


In [ ]:
for i, value in enumerate(fruits_copy):
  print("The fruits at position {} is {}" .format(i, value))

The fruits at position 0 is sugarcane
The fruits at position 1 is pineapple
The fruits at position 2 is orange
The fruits at position 3 is mango
The fruits at position 4 is grapes
The fruits at position 5 is blueberry
The fruits at position 6 is apple
The fruits at position 7 is alphonso


In [ ]:
education = ['10th', '12th', 'graduation', 'post graduation', 'phd']

for i in education:
  print("I have completed my {}" .format(i))
  if i == 'graduation':
    print("I don't want to study further!")
    break

I have completed my 10th
I have completed my 12th
I have completed my graduation
I don't want to study further!


In [ ]:
events = ['freshers party', 'conference', 'hackathon', 'farewell party', 'national event']

for i in events:
  if i == 'freshers party':
    print("I don't want to participate in {}" .format(i))
    continue
  print("I will participate in {}" .format(i))

I don't want to participate in freshers party
I will participate in conference
I will participate in hackathon
I will participate in farewell party
I will participate in national event


In [ ]:
for i in animals: # a loop cannot be empty
  pass # so we ignore the loop simply by using pass keyword

#### **Working with Functions()**

In [ ]:
def greet(name):
  print("Hello {} this is my first function!" .format(name))

In [ ]:
greet("Abdulkadar")

Hello Abdulkadar this is my first function!


In [ ]:
# filter even numbers
def filter_even(number_list):
  store = []
  for i in number_list:
    if i % 2 == 0:
      store.append(i)
  return store

In [ ]:
filter_even([2,3,6,5,4,7,8,23,51,86,74,20,59,74])

[2, 6, 4, 8, 86, 74, 20, 74]

In [ ]:
# filter odd numbers
def filter_odd(number_list):
  store = []
  for i in number_list:
    if i % 2 != 0:
      store.append(i)
  return store

In [ ]:
filter_odd([1,2,3,4,5,6,7,8,9,10,12,15,18])

[1, 3, 5, 7, 9, 15]

In [ ]:
# Q.1)

# house = 1260000

# # option 1
# down_payment = 300000
# loan = 960000
# period = '8 years'
# rate = .10 # compounded monthly for the remaining amount

# # option 2
# loan = 1260000
# period = '10 years'
# rate = .08 # compounded monthly for the entire amount

# which option has the lowest EMI ?

In [ ]:
# here emi is a local variable and it's scope is within the function
def loan_emi(amt):
  emi = amt / 12
  print("The EMI is ${}" .format(emi))
  
loan_emi(1260000)

The EMI is $105000.0


In [ ]:
def loan_emi(amount, duration):
  emi = amount / (duration * 12)
  print("The EMI is ${} for the duration of {} years" .format(emi, duration))

loan_emi(1260000, 8)
loan_emi(1260000, 10)

The EMI is $13125.0 for the duration of 8 years
The EMI is $10500.0 for the duration of 10 years


In [ ]:
def calc_emi(amount, duration):
  emi = amount / (duration * 12)
  return emi # return the value rather than printing

emi_8years = calc_emi(1260000, 8)
emi_10years = calc_emi(1260000, 10)

In [ ]:
emi_8years

13125.0

In [ ]:
emi_10years

10500.0

In [ ]:
emi_8years - emi_10years

2625.0

In [ ]:
def loan_emi(amount, duration, down_payment = 0):
  loan_amount = amount - down_payment
  emi = loan_amount / (duration * 12)
  return emi

loan_emi(1260000, 8, 300000)

10000.0

Interest Calculation Formula

Where:
* p = loan amount(principal)
* n = no. of months
* r = rate of interest per month

In [ ]:
def loan_emi(amount, duration, rate, down_payment = 0):
  """Calculates the Equal Monthly Installment (EMI) for a loan.

  Arguments:
    amount - Total amount to be spent (loan + down payment)
    duration - Duration of the loan (in months)
    rate - Rate of interest (monthly)
    down_payment - (optional parameter) - optional initial payment (deducted from amount)
  """
  loan_amount = amount - down_payment
  try:
    emi = amount * rate * ((1 + rate) ** (duration*12)) / (((1 + rate) ** (duration*12)) -1)
  except ZeroDivisionError:
    emi = loan_amount / duration
  return round(emi, 2)

In [ ]:
option1 = loan_emi(1260000, 8, 0.1/12, 300000)
option1

19119.45

In [ ]:
option2 = loan_emi(1260000, 10, 0.08/12)
option2

15287.28

In [ ]:
emi_1 = loan_emi(
    duration = 8,
    amount = 1260000,
    rate = .10/12,
    down_payment = 300000
)

In [ ]:
emi_1

19119.45

In [ ]:
emi_2 = loan_emi(amount = 1260000, duration = 10, rate = 0.08/12)

In [ ]:
emi_2

15287.28

In [ ]:
if emi_1 > emi_2:
  print("option 1 has the highest EMI: ${} \nso it's better to go with the option 2 with EMI: ${}" .format(emi_1, emi_2))
else:
  print("option 2 has the highest EMI: ${} so it's better to go with the option 1 with EMI: ${}" .format(emi_2, emi_1))

option 1 has the highest EMI: $19119.45 
so it's better to go with the option 2 with EMI: $15287.28


In [ ]:
# Q.2)
house_cost = 800000
loan_tenure = 6
int_rate = 0.07/12
downpayment = .25 * 800000

house_emi = loan_emi(house_cost, loan_tenure, int_rate, downpayment)

house_emi

13639.21

In [ ]:
# Q.3)
car_cost = 60000
loan_duration = 1
loan_rate = .12/12

emi_car = loan_emi(amount = car_cost, duration = loan_duration, rate = loan_rate)

emi_car

5330.93

In [ ]:
print("Arun makes a total monthly payment of ${} towards loan repayments." .format(house_emi + emi_car))

Arun makes a total monthly payment of $18970.14 towards loan repayments.


In [ ]:
emi_with_Interest = loan_emi(amount = 100000, duration = 10, rate = 0.09/12)
emi_with_Interest

1266.76

In [ ]:
emi_without_Interest = loan_emi(amount = 100000, duration = 10*12, rate = 0)
emi_without_Interest

833.33

In [ ]:
try:
  print("Now computing the result....")
  result = 5/2
  print("Computation was completed successfully")
except ZeroDivisionError:
  print("Failed to compute the result because you are trying to divide by zero")
  result = None

print(result)

Now computing the result....
Computation was completed successfully
2.5


In [ ]:
# Exercise Cost of Trip

def cost_of_trip(city, flight_cost, hotel_rent, car_rental, duration = 0, budget = 0):
  total_cost = (flight_cost + (hotel_rent * duration) + (car_rental / 7) * duration)
  remaining_amount = budget - total_cost
  if budget == 0:
    print("To travel {} the total cost incurred = ${}.\n" .format(city, round(total_cost)))
  else:
    print("To travel {} the total_cost = ${}.\nAnd the remaining budget subtracted by total_cost = ${}.\n" .format(city, round(total_cost), round(remaining_amount)))

In [ ]:
# Q.1) Paris has the least cost for a week to visit.
# 1 week

cost_of_trip("Paris", 200, 20, 200, 7)
cost_of_trip("London", 250, 30, 120, 7)
cost_of_trip("Dubai", 370, 15, 80, 7)
cost_of_trip("Mumbai", 450, 10, 70, 7)

To travel Paris the total cost incurred = $540.

To travel London the total cost incurred = $580.

To travel Dubai the total cost incurred = $555.

To travel Mumbai the total cost incurred = $590.



In [ ]:
# 4 days

cost_of_trip("Paris", 200, 20, 200, 4)
cost_of_trip("London", 250, 30, 120, 4)
cost_of_trip("Dubai", 370, 15, 80, 4)
cost_of_trip("Mumbai", 450, 10, 70, 4)

To travel Paris the total cost incurred = $394.

To travel London the total cost incurred = $439.

To travel Dubai the total cost incurred = $476.

To travel Mumbai the total cost incurred = $530.



In [ ]:
# 10 days

cost_of_trip("Paris", 200, 20, 200, 10)
cost_of_trip("London", 250, 30, 120, 10)
cost_of_trip("Dubai", 370, 15, 80, 10)
cost_of_trip("Mumbai", 450, 10, 70, 10)

To travel Paris the total cost incurred = $686.

To travel London the total cost incurred = $721.

To travel Dubai the total cost incurred = $634.

To travel Mumbai the total cost incurred = $650.



In [ ]:
# 2 weeks

cost_of_trip("Paris", 200, 20, 200, 14)
cost_of_trip("London", 250, 30, 120, 14)
cost_of_trip("Dubai", 370, 15, 80, 14)
cost_of_trip("Mumbai", 450, 10, 70, 14)

To travel Paris the total cost incurred = $880.

To travel London the total cost incurred = $910.

To travel Dubai the total cost incurred = $740.

To travel Mumbai the total cost incurred = $730.



In [ ]:
# Q.3)
# With total budget = $1000 a person can travel to mumbai for 27 days (Maximum).
# With total cost = $990 and the remaining budget = $10

cost_of_trip("Paris", 200, 20, 200, 27, 1000)
cost_of_trip("London", 250, 30, 120, 27, 1000)
cost_of_trip("Dubai", 370, 15, 80, 27, 1000)
cost_of_trip("Mumbai", 450, 10, 70, 27, 1000)

To travel Paris the total_cost = $1511.
And the remaining budget subtracted by total_cost = $-511.

To travel London the total_cost = $1523.
And the remaining budget subtracted by total_cost = $-523.

To travel Dubai the total_cost = $1084.
And the remaining budget subtracted by total_cost = $-84.

To travel Mumbai the total_cost = $990.
And the remaining budget subtracted by total_cost = $10.



In [ ]:
# With total cost = $957 a person can visit to London for 15 days (Minimum).
# And the remaining budget = $43

cost_of_trip("Paris", 200, 20, 200, 15, 1000)
cost_of_trip("London", 250, 30, 120, 15, 1000)
cost_of_trip("Dubai", 370, 15, 80, 15, 1000)
cost_of_trip("Mumbai", 450, 10, 70, 15, 1000)

To travel Paris the total_cost = $929.
And the remaining budget subtracted by total_cost = $71.

To travel London the total_cost = $957.
And the remaining budget subtracted by total_cost = $43.

To travel Dubai the total_cost = $766.
And the remaining budget subtracted by total_cost = $234.

To travel Mumbai the total_cost = $750.
And the remaining budget subtracted by total_cost = $250.



In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [ ]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43


In [ ]:
kanto_yield_Apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
print("The expected yield of apples in kanto region is {} tons per hectare." .format(kanto_yield_Apples))

The expected yield of apples in kanto region is 56.8 tons per hectare.


In [ ]:
# Makeing it a bit simpler
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1, w2, w3]

def crop_yeild(region, weights):
  result = 0
  for r, w in zip(region, weights):
    result += r * w
  return result

In [ ]:
kanto

[73, 67, 43]

In [ ]:
weights

[0.3, 0.2, 0.5]

In [ ]:
for items in zip(kanto, weights): # creates a pair zip()
  print(items)

(73, 0.3)
(67, 0.2)
(43, 0.5)


In [ ]:
print(crop_yeild(johto, weights))
print(crop_yeild(kanto, weights))

76.9
56.8


**Modules and Libraries**

* Modules are files containing python code (variable, functions, classes etc.)
* They provide a way of organizing the code for large python projects into files and folders.
* A module first has to be imported with their namespace before it can be used.

In [ ]:
import numpy as np

In [ ]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [ ]:
np.dot(kanto, weights)

56.8

In [ ]:
kanto = np.array(kanto)
kanto

array([73, 67, 43])

In [ ]:
weights = np.array(weights)
weights

array([0.3, 0.2, 0.5])

In [ ]:
type(kanto)
type(weights)

numpy.ndarray

In [ ]:
(kanto * weights).sum()

56.8

In [ ]:
# python list
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1 * x2
result

CPU times: user 353 ms, sys: 0 ns, total: 353 ms
Wall time: 354 ms


833332333333500000

In [ ]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 1.91 ms, sys: 0 ns, total: 1.91 ms
Wall time: 6.93 ms


833332333333500000

In [ ]:
climate_data = np.array([kanto, johto, hoenn, sinnoh, unova])
climate_data # it's a matrix

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
climate_data.shape

(5, 3)

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print("This is a 1D or dimensional array:", arr1)

This is a 1D or dimensional array: [1 2 3 4 5]


In [ ]:
print("This is a 2D or dimensional array:\n", climate_data)

This is a 2D or dimensional array:
 [[ 73  67  43]
 [ 91  88  64]
 [ 87 134  58]
 [102  43  37]
 [ 69  96  70]]


In [ ]:
arr3 = np.array([
    [[11, 12, 13],
     [14, 15, 16]],
    
    [[2, 4, 6],
    [8, 10, 12]]])

print("This is a 3D or dimensional array:\n", arr3)

This is a 3D or dimensional array:
 [[[11 12 13]
  [14 15 16]]

 [[ 2  4  6]
  [ 8 10 12]]]


In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
weights.dtype

dtype('float64')

In [ ]:
climate_data.dtype

dtype('int64')

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
# @ character represent the matrix multiplication in numpy
yields = climate_data @ weights 

In [ ]:
climate_data.shape

(5, 3)

In [ ]:
climate_results = np.concatenate((climate_data, yields.reshape(5,1)), axis = 1)
climate_results

array([[ 73. ,  67. ,  43. ,  56.8],
       [ 91. ,  88. ,  64. ,  76.9],
       [ 87. , 134. ,  58. ,  81.9],
       [102. ,  43. ,  37. ,  57.7],
       [ 69. ,  96. ,  70. ,  74.9]])

In [ ]:
climate_results.shape

(5, 4)

In [ ]:
# saves the climate_results as a txt file
np.savetxt('climate_results.txt',
            climate_results,
            fmt = '%.2f',
            header = "temperature, rainfall, humidity, yield_apples",
            comments = " ")

In [ ]:
arr2 = np.array([[1, 2, 3, 4],
                 [6, 7, 8, 9],
                 [5, 6, 7, 8]])

arr3 = np.array([[10, 12, 13, 14],
                [15, 16, 17, 18],
                [19, 20, 21, 22]])

In [ ]:
arr2 + arr3

array([[11, 14, 16, 18],
       [21, 23, 25, 27],
       [24, 26, 28, 30]])

In [ ]:
# adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 9, 10, 11, 12],
       [ 8,  9, 10, 11]])

In [ ]:
# subtracting a scalar
arr2 - 3

array([[-2, -1,  0,  1],
       [ 3,  4,  5,  6],
       [ 2,  3,  4,  5]])

In [ ]:
# dividing a scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [3. , 3.5, 4. , 4.5],
       [2.5, 3. , 3.5, 4. ]])

In [ ]:
# element wise subtraction
arr2 - arr3

array([[ -9, -10, -10, -10],
       [ -9,  -9,  -9,  -9],
       [-14, -14, -14, -14]])

In [ ]:
arr2 * arr3

array([[ 10,  24,  39,  56],
       [ 90, 112, 136, 162],
       [ 95, 120, 147, 176]])

In [ ]:
arr2 % arr3

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [5, 6, 7, 8]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[2, 2, 4], [4, 6, 6]])

In [ ]:
arr1 == arr2

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
(arr1 == arr2).dtype

dtype('bool')

In [ ]:
arr1 >= arr2

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
arr2 < arr1

array([[False, False, False],
       [False, False, False]])

In [ ]:
# True = 1 & False = 0
(arr1 == arr2).sum() # returns 3 of true values

3

In [ ]:
arr3 = np.array([
    [[1, 2, 3, 4],
      [2, 3, 4, 7]],
      
      [[3, 2, 4, 5],
       [8, 9, 5, 3]],

       [[6, 3, 4, 7],
        [9, 2, 3, 5]]])

In [ ]:
arr3.shape

(3, 2, 4)

In [ ]:
arr3[1, 1, 3]

3

In [ ]:
arr3

array([[[1, 2, 3, 4],
        [2, 3, 4, 7]],

       [[3, 2, 4, 5],
        [8, 9, 5, 3]],

       [[6, 3, 4, 7],
        [9, 2, 3, 5]]])

In [ ]:
arr3[1:, 0:1, :2]

array([[[3, 2]],

       [[6, 3]]])

In [ ]:
arr3[1:]

array([[[3, 2, 4, 5],
        [8, 9, 5, 3]],

       [[6, 3, 4, 7],
        [9, 2, 3, 5]]])

In [ ]:
arr3[1:, :1]

array([[[3, 2, 4, 5]],

       [[6, 3, 4, 7]]])

In [ ]:
arr3[1:, 1:2, 0:2]

array([[[8, 9]],

       [[9, 2]]])

In [ ]:
# Another way to create arrays
# all zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# all ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# random vector
np.random.rand(5) # uniform values

array([0.1355425 , 0.75245335, 0.6689809 , 0.03550599, 0.90377043])

In [ ]:
np.random.randn(5, 3) # normal/gaussian distribution

array([[-0.6788149 , -1.77633779, -0.36595434],
       [ 1.26046581, -0.10966243, -0.04998054],
       [ 1.78437884, -1.04522609, -0.597079  ],
       [ 0.47565743,  0.54631695,  0.3179842 ],
       [ 0.38062271,  0.30410451,  1.42925243]])

In [ ]:
# fixed value
np.full([2,3], 24)

array([[24, 24, 24],
       [24, 24, 24]])

In [ ]:
# range with start, end, step
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.arange(10, 50, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [ ]:
np.arange(10, 50, 3).shape

(14,)

In [ ]:
np.arange(10, 30).reshape(4,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
# equally spaced numbers
np.linspace(4, 50, 6)

array([ 4. , 13.2, 22.4, 31.6, 40.8, 50. ])

In [ ]:
arr2 = np.arange(0, 9).reshape(3, 3)

In [ ]:
arr3 = np.arange(10, 19).reshape(3, 3)

In [ ]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr3

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
# concatenate vertically
np.vstack((arr2, arr3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
# concatenate horizontally
np.hstack((arr2, arr3)) 

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [ ]:
# split array
x = np.arange(1, 31).reshape(3, 10)

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
# splitted into two equal parts
np.hsplit(x, 2) 

[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20],
        [26, 27, 28, 29, 30]])]

In [ ]:
np.hsplit(x, (3, 2))

[array([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]]),
 array([], shape=(3, 0), dtype=int64),
 array([[ 3,  4,  5,  6,  7,  8,  9, 10],
        [13, 14, 15, 16, 17, 18, 19, 20],
        [23, 24, 25, 26, 27, 28, 29, 30]])]

In [ ]:
x.max()

30

In [ ]:
x.min()

1

In [ ]:
x.sum()

465

In [ ]:
x.min(axis = 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x.max(axis = 0)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
x.sum(axis = 0) # sum over the rows

array([33, 36, 39, 42, 45, 48, 51, 54, 57, 60])

In [ ]:
x.sum(axis = 1) # sum over the columns

array([ 55, 155, 255])

In [ ]:
# random array generator
rng = np.random.default_rng(12345)

In [ ]:
rng.integers(10, size = (3, 3))

array([[6, 2, 7],
       [3, 2, 7],
       [6, 6, 9]])

In [ ]:
rng.integers(low = 1, high = 18, size = 10)

array([ 7, 15,  6, 10, 11,  4,  4,  4, 12, 11])

In [ ]:
rng.permutation(10)

array([8, 0, 6, 2, 4, 1, 3, 7, 5, 9])

In [ ]:
x[x % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
x[x % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
x[x <  (6 + 3)]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x[(x > 5) & (x < 10)]

array([6, 7, 8, 9])

In [ ]:
b = np.nonzero(arr2 < 5)

In [ ]:
list_of_coord = list(zip(b[0], arr2[1]))

for coord in list_of_coord:
  print(coord)

(0, 3)
(0, 4)
(0, 5)


In [ ]:
a = rng.integers(low = 1, high = 6, size = (9, 9))

In [ ]:
a

array([[4, 2, 2, 1, 4, 4, 2, 4, 1],
       [2, 1, 4, 2, 3, 3, 3, 2, 3],
       [5, 3, 1, 1, 1, 1, 1, 1, 3],
       [5, 5, 4, 4, 2, 5, 4, 4, 4],
       [5, 4, 5, 3, 3, 2, 5, 3, 3],
       [2, 2, 4, 3, 3, 4, 5, 2, 4],
       [5, 3, 2, 2, 2, 4, 2, 5, 2],
       [1, 1, 1, 4, 2, 2, 4, 1, 3],
       [4, 1, 1, 2, 2, 5, 3, 4, 1]])

In [ ]:
unique_values = np.unique(a)

In [ ]:
unique_values = list(unique_values)

In [ ]:
type(unique_values)

list

In [ ]:
unique_values

[1, 2, 3, 4, 5]

In [ ]:
np.unique(a, return_index= True) # returns the index position of unique values

(array([1, 2, 3, 4, 5]), array([ 3,  1, 13,  0, 18]))

In [ ]:
np.unique(a, return_counts = True) # returns the total occurence of unique values

(array([1, 2, 3, 4, 5]), array([16, 20, 15, 19, 11]))

In [ ]:
unique_rows = np.unique(a, axis = 0)
unique_rows

array([[1, 1, 1, 4, 2, 2, 4, 1, 3],
       [2, 1, 4, 2, 3, 3, 3, 2, 3],
       [2, 2, 4, 3, 3, 4, 5, 2, 4],
       [4, 1, 1, 2, 2, 5, 3, 4, 1],
       [4, 2, 2, 1, 4, 4, 2, 4, 1],
       [5, 3, 1, 1, 1, 1, 1, 1, 3],
       [5, 3, 2, 2, 2, 4, 2, 5, 2],
       [5, 4, 5, 3, 3, 2, 5, 3, 3],
       [5, 5, 4, 4, 2, 5, 4, 4, 4]])

In [ ]:
unique_rows, indices, occurence_count = np.unique(a, axis = 0, return_counts = True, return_index = True)

print("The unique rows are: ", unique_rows, '\n' "The index: ", indices, '\n' "The total occurence: ", occurence_count)


The unique rows are:  [[1 1 1 4 2 2 4 1 3]
 [2 1 4 2 3 3 3 2 3]
 [2 2 4 3 3 4 5 2 4]
 [4 1 1 2 2 5 3 4 1]
 [4 2 2 1 4 4 2 4 1]
 [5 3 1 1 1 1 1 1 3]
 [5 3 2 2 2 4 2 5 2]
 [5 4 5 3 3 2 5 3 3]
 [5 5 4 4 2 5 4 4 4]] 
The index:  [7 1 5 8 0 2 6 4 3] 
The total occurence:  [1 1 1 1 1 1 1 1 1]


In [ ]:
arr3

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
arr3.transpose()

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [ ]:
arr3.T

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [ ]:
b = np.arange(1, 7)

In [ ]:
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
reversed_array = np.flip(b) # to reverse an array

In [ ]:
reversed_array

array([6, 5, 4, 3, 2, 1])

In [ ]:
str_array = np.array(fruits_copy)
str_array

array(['sugarcane', 'pineapple', 'orange', 'mango', 'grapes', 'blueberry',
       'apple', 'alphonso'], dtype='<U9')

In [ ]:
np.chararray.isalpha(str_array)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
np.chararray.swapcase(str_array)

chararray(['SUGARCANE', 'PINEAPPLE', 'ORANGE', 'MANGO', 'GRAPES',
           'BLUEBERRY', 'APPLE', 'ALPHONSO'], dtype='<U9')

In [ ]:
np.chararray.title(str_array)

chararray(['Sugarcane', 'Pineapple', 'Orange', 'Mango', 'Grapes',
           'Blueberry', 'Apple', 'Alphonso'], dtype='<U9')

In [ ]:
np.resize(str_array, (2,4))

array([['sugarcane', 'pineapple', 'orange', 'mango'],
       ['grapes', 'blueberry', 'apple', 'alphonso']], dtype='<U9')

In [ ]:
np.chararray.replace(str_array, 'mango', 'kela') # rplaces the element from the string array

chararray(['sugarcane', 'pineapple', 'orange', 'kela', 'grapes',
           'blueberry', 'apple', 'alphonso'], dtype='<U9')

In [ ]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2[0,0] = 21
arr2[0,1] = 45
arr2

array([[21, 45,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
new_arr2 = arr2.flatten()
print(new_arr2)
print("size of the array: ", new_arr2.size)
print("memory size of one array element in bytes: ", new_arr2.itemsize)
print("memory size of numpy array in byes: ", new_arr2.size * new_arr2.itemsize)

[21 45  2  3  4  5  6  7  8]
size of the array:  9
memory size of one array element in bytes:  8
memory size of numpy array in byes:  72


In [ ]:
print(np.__version__)

1.22.4


In [ ]:
help(arr2.flatten)

Help on built-in function flatten:

flatten(...) method of numpy.ndarray instance
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.
    
    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.
    
    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.
    
    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4]

In [ ]:
null_vect = np.zeros(10)
null_vect[4] = 1
print(null_vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
vect = np.arange(10, 49+1)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
np.flip(vect)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
print(np.arange(0,8+1).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
c = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(c) # return indices of non zeros

(array([0, 1, 4]),)

In [ ]:
def print_checkerboard(n):
  print("Checkerboard Pattern: ")

  x = np.zeros((n,n), dtype = int)

  x[1::2, ::2] = 1
  x[::2, 1::2] = 1

  for i in range(n):
    for j in range(n):
      print(x[i][j], end = " ")
    print()

n = 8
print_checkerboard(n)

Checkerboard Pattern: 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


**Interacting with the OS & File System**

In [ ]:
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
os.listdir()

['.config', 'climate_results.txt', 'sample_data']

In [ ]:
# relative path
os.listdir('.') # shows the current working directory

['.config', 'climate_results.txt', 'sample_data']

In [ ]:
os.makedirs('./Data', exist_ok = True)

In [ ]:
help(os.makedirs)

Help on function makedirs in module os:

makedirs(name, mode=511, exist_ok=False)
    makedirs(name [, mode=0o777][, exist_ok=False])
    
    Super-mkdir; create a leaf directory and all intermediate ones.  Works like
    mkdir, except that any intermediate path segment (not just the rightmost)
    will be created if it does not exist. If the target directory already
    exists, raise an OSError if exist_ok is False. Otherwise no exception is
    raised.  This is recursive.



In [ ]:
'Data' in os.listdir('.')

True

In [ ]:
import urllib.request

In [ ]:
dataset_url = 'https://www.kaggle.com/datasets/spscientist/students-performance-in-exams?select=StudentsPerformance.csv' 

In [ ]:
# !pip install opendatasets

In [ ]:
import opendatasets as od

# To download the file from the url or internet
od.download_url(dataset_url, root = './Data', filename = 'Exams.csv')

Using downloaded and verified file: ./Data/Exams.csv


In [ ]:
os.listdir('./Data')

['Exams.csv']

In [322]:
os.remove('./Data/Exams.csv') # removes a file from a given location

In [ ]:
# file1 = open('./Data/Exams.csv', mode = 'r')

In [323]:
# file1_contents = file1.read()
#  file1_contents

In [324]:
# 

['exams.csv']